---

- name: setup torns
  hosts: torns.lsferreira.net
  roles:
    - { role: common, tags: ['common'] }
    - { role: users, tags: ['users'] }
    - { role: ssh_root, tags: ['ssh_root'] }
    - { role: sudo, tags: ['sudo'] }
    - { role: firewall, tags: ['firewall'] }
    - { role: raid, tags: ['raid'] }
    - { role: samba, tags: ['samba'] }
    - { role: syncrepo, tags: ['syncrepo'] }
    - { role: lighttpd, tags: ['lighttpd'] }
